repos:
  - repo: local
    hooks:
      - id: eslint-fix
        name: eslint --fix
        entry: npx eslint --fix .
        language: system
        pass_filenames: false
        types: [javascript] 