name: PR Build

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

permissions:
  contents: read
  issues: read

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  validate-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check for required labels
        id: check_labels
        run: |
          LABELS=$(echo '${{ toJSON(github.event.pull_request.labels) }}' | jq -r '.[].name' | tr '\n' ' ')
          REQUIRED_LABELS=("version:major" "version:minor" "version:patch")

          VERSION_LABEL_COUNT=0
          FOUND_LABEL=""
          for label in "${REQUIRED_LABELS[@]}"; do
            if [[ "$LABELS" == *"$label"* ]]; then
              VERSION_LABEL_COUNT=$((VERSION_LABEL_COUNT + 1))
              FOUND_LABEL="$label"
            fi
          done

          if [[ "$VERSION_LABEL_COUNT" -eq 0 ]]; then
            echo "❌ ERROR: Pull request must have exactly one of the following labels:"
            echo "   - version:major"
            echo "   - version:minor"
            echo "   - version:patch"
            echo ""
            echo "Current labels: $LABELS"
            exit 1
          elif [[ "$VERSION_LABEL_COUNT" -gt 1 ]]; then
            echo "❌ ERROR: Multiple version labels found: $LABELS"
            exit 1
          else
            echo "✅ Found: $FOUND_LABEL"
            echo "labels=$LABELS" >> $GITHUB_OUTPUT
            echo "version_label=$FOUND_LABEL" >> $GITHUB_OUTPUT
          fi

  build-test:
    runs-on: ubuntu-latest
    needs: validate-labels

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js and enable cache
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # npm ci automatically uses cache when setup-node includes cache: 'npm'
      - name: Install dependencies
        run: npm ci --verbose

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Lint
        run: npm run lint

      - name: Run integration tests
        run: xvfb-run --auto-servernum --server-args='-screen 0 1280x1024x24' npm run test:integration
